---
# tasks file for docker-watchtower

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Recreate watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    ports:
      - '5299:5299/tcp'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      VERSION: "latest"
    command:
      - 'schedule "0 0 * * * "'
      - "cleanup"
  tags:
    - watchtower
