- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Download cache_domains.json
      get_url:
        url: "{{globalURL}}{{cacheDomain}}"
        dest: files/cache/cache_domains.json

    - name: Read JSON file (can also be a variable).
      shell: cat files/cache/cache_domains.json
      register: json
      failed_when: ("No such file or directory" in json.stdout) 
      changed_when: false 

    - name: Download Files
      get_url:
        url: "{{globalURL}}{{item.domain_files[0]}}"
        dest: "./files/cache/{{item.domain_files[0]}}"
      with_items:
        - "{{ (json.stdout| from_json).cache_domains}}"
      loop_control:
        label: "{{ item.name  }}"


    - name: Reading DNS info
      set_fact:
        cacheable: yes
        dns_info: "{{ dns_info|default([]) + 
          [{
          'name' : item.name, 
          'file' : item.domain_files[0],
          'dns_entry': lookup('file', './files/cache/' + item.domain_files[0]).splitlines()
          }]
        }}"
      with_items:
        - "{{ (json.stdout| from_json).cache_domains}}"
      loop_control:
        label: "{{ item.name  }}"

#    - name: Simple debug.
#      debug:
#        msg: "{{ item }}"
#      with_items: "{{ dns_info }}"

    - name: Creating zone files
      template:
        src: zone.j2
        dest: "temp/{{item.name}}.hosts"
      with_items: "{{ dns_info }}"
     #notify: reload bind
      tags: [ 'zones' ]
      loop_control:
        label: "{{ item.name  }}"


  vars:
    cacheDomain: "cache_domains.json"
    globalURL: "https://raw.githubusercontent.com/uklans/cache-domains/master/"
#    blizzard_value: "{{ lookup('file', 'blizzard.txt').splitlines() }}"
