---
# tasks file for docker-pi-alert
# https://registry.hub.docker.com/r/jokobsk/pi.alert

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{docker_pi_alert_storage}}{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - data
  tags:
    - pihole

- name: Recreate pi-alert container
  community.docker.docker_container:
    name: pi-alert
    hostname: "{{docker_pihole_virtual_hostname}}"
    image: jokobsk/pi.alert:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    shm_size: 500Mb
    ports: []
      # - "53:53/tcp"
      # - "8888:80/tcp"
      # - "53:53/udp"
    exposed_ports:
      - "20211/tcp"
    volumes:
      - "{{docker_pi_alert_storage}}/data/db/:/home/pi/pialert/db"
      - "{{docker_pi_alert_storage}}/data/pialert.conf:/home/pi/pialert/config/pialert.conf"
      - "{{docker_pi_alert_storage}}/data/version.conf:/home/pi/pialert/config/version.conf"
      - /etc/localtime:/etc/localtime:ro
    networks_cli_compatible: false
    networks:
      - name: theways
      - name: local
          ipv
    env:
      TZ: "America/Chicago"
      VIRTUAL_HOST: "{{ docker_pihole_virtual_host }}"
      hostname: "{{docker_pihole_virtual_hostname}}"
    dns_servers:
      - 10.1.1.1
      - 1.1.1.1
  tags:
    - pihole