---
# tasks file for docker-dns
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_unifi_storage }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - /config
  tags:
    - unifi

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/unifi-controller.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/unifi-controller.subdomain.conf"
    mode: '0440'
  tags:
    - unifi
    - SWAG
  notify:
    - restart SWAG

- name: Recreate Unifi container
  community.docker.docker_container:
    name: unifi-controller
    # image: jacobalberty/unifi:latest
    image: ghcr.io/linuxserver/unifi-controller
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8443"
      - "8080"
      - "3478/udp"
    published_ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "1900:1900/udp"
      - "8080:8080/tcp"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    volumes:
      - "{{ docker_unifi_storage }}/config:/config"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: America/Chicago
      PUID: "1000"
      PGID: "1000"
  tags:
    - unifi