---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_prowlarr_storage }}{{ item }}"
    state: directory
  with_items:
    - config

- name: Recreate prowlarr container
  community.docker.docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '9696'
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - "{{ docker_prowlarr_storage }}/config:/config"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - prowlarr

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/prowlarr.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/prowlarr.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG