---
# Apply common configuration to all hosts
- hosts: all
  become: true
  remote_user: joe
  roles:
    - basic-server
    - zsh
    # - geerlingguy.pip
    # - geerlingguy.docker
  vars_files:
    - vars/main.yml
    - vars/vault_setup

