---
- hosts: all
  become: true
  remote_user: joe
  roles:
    - basic-server
    - zsh
    - geerlingguy.pip
    - geerlingguy.docker
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault_setup

- hosts: getting
  become: true
  remote_user: ansible
  roles:
    - docker-proxy
#     - docker-uptime-kuma
    - docker-sonarr
      # - docker-radarr
#     - docker-signal-messager
#     - docker-piHole-Influx
#     - docker-tautlli
#     - docker-varken
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault