---
#Apply common configuration to all hosts
- hosts: v-docker01.telaranrhiod.space:v-docker02.telaranrhiod.space
  become: true
  remote_user: joe
  roles:
    - docker-dns
    # - basic-server
    # - zsh
    # - geerlingguy.docker
    # - docker-common
    # - docker-watchtower
  vars_files:
    - vars/main.yml
    - vars/vault
    # - zsh
#    - docker-influxDB
#   vars:
#     pip_install_packages:
#       - name: docker

# - hosts: stats
#   become: true
#   remote_user: it
#   roles:
#     - basic-server
#     - geerlingguy.docker
#     - docker-influxDB
#   vars_files:
#     - vars/main.yml
#     - vars/vault
#     # - zsh
# #    - docker-influxDB


#  - hosts: cluster
#    become: true
#    roles:
#      - basic-server
#      - zsh
#    - docker-common
#    - geerlingguy.docker
#    - docker-sonarr
#    - docker-radarr
#    - docker-transmission
#    - docker-jackett
#  vars:
#    pip_install_packages:
#      - name: docker

# - hosts: watching
#   become: true
#   remote_user: joe
#   roles:
#     - geerlingguy.docker
#     - docker-sonarr
#     - docker-radarr
#     - docker-transmission
#     - docker-jackett
#     - docker-dns

# - hosts: getting
#   become: true
#   remote_user: joe
#   roles:
#     - geerlingguy.docker
#     - docker-sonarr
#     - docker-radarr
#     # - docker-transmission
#     - docker-jackett
#     - docker-dns
