---
#Apply common configuration to all hosts
- hosts: home
  become: true
  roles:
    # - basic-server
    # - zsh
    # - docker-common
    # - geerlingguy.docker
    # - docker-grafana
    # - docker-unifi
    # - docker-influxDB
    - docker-sonarr
    - docker-radarr
    - docker-transmission
    - docker-jackett
  vars:
    pip_install_packages:
      - name: docker
    # - docker-dns
    # - geerlingguy.ntp

- hosts: docker02
  become: true
  roles:
    - basic-server
    - zsh
    - docker-common
    - geerlingguy.docker
    # - docker-grafana
    # - docker-unifi
    # - docker-influxDB
    - docker-sonarr
    - docker-radarr
    - docker-transmission
    - docker-jackett
  vars:
    pip_install_packages:
      - name: docker
    # - docker-dns
    # - geerlingguy.ntp


# - hosts: streaming
#   become: true
#   roles:
#     # - basic-server
#     - zsh
#     - docker-LibreNMS
#     # - geerlingguy.ntp
#     # - docker-plex
#     # - docker-plexpy

# - hosts: getting
#   become: true
#   # remote_user: it
#   roles:
