---
# - hosts: all
#   become: true
#   remote_user: joe
#   roles:
#     - basic-server
#     - zsh
#     - geerlingguy.pip
#     - geerlingguy.docker
#   vars:
#     - ansible_python_interpreter: "/usr/bin/python3"
#   vars_files:
#     - vars/main.yml
#     - vars/vault_setup

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    # - docker-unifi
    - docker-proxy
    - docker-uptime-kuma
    - docker-dashy
    - {
        role: docker-piHole,
        pihole_virtual_hostname: "pihole01",
        pihole_virtual_host: "pihole01.telaranrhiod.space",
      }
    # - docker-librespeed
    - docker-vaultwarden
    # - docker-piHole-Influx
    # - docker-grafana
    - docker-jackett
    # - docker-minecraft
    # - docker-prometheus
    # - docker-tautlli
    # - docker-varken
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault

- hosts: getting
  become: true
  remote_user: ansible
  roles:
    - docker-proxy
    - {
      role: docker-piHole,
      pihole_virtual_hostname: "pihole02",
      pihole_virtual_host: "pihole02.telaranrhiod.space",
    }
    - docker-overseerr
    - docker-sonarr
    - docker-radarr
#     - docker-signal-messager
#     - docker-piHole-Influx
#     - docker-tautlli
#     - docker-varken
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault

# - hosts: stats
#   become: true
#   remote_user: it
#   roles:
#     # - docker-proxy
#     # - docker-influxDB
#     - docker-LibreNMS
#   vars:
#     - ansible_python_interpreter: "/usr/bin/python"
#   vars_files:
#     - vars/main.yml
#     - vars/vault
- hosts: torrents
  become: true
  remote_user: ansible
  roles:
    - docker-proxy
    - docker-deluge
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault