---
#Apply common configuration to all hosts
- hosts: home
  become: true
  remote_user: joe
  roles:
    - basic-server
    - geerlingguy.docker
    - docker-common
    - docker-dns
  vars_files:
    - vars/main.yml
    - vars/vault
    # - zsh
#    - docker-influxDB
#   vars:
#     pip_install_packages:
#       - name: docker
#     # - docker-dns
#     # - geerlingguy.ntp

- hosts: stats
  become: true
  remote_user: it
  roles:
    - basic-server
    - geerlingguy.docker
    - docker-influxDB
  vars_files:
    - vars/main.yml
    - vars/vault
    # - zsh
#    - docker-influxDB



#  - hosts: cluster
#    become: true
#    roles:
#      - basic-server
#      - zsh
#    - docker-common
#    - geerlingguy.docker
#    - docker-sonarr
#    - docker-radarr
#    - docker-transmission
#    - docker-jackett
#  vars:
#    pip_install_packages:
#      - name: docker
    # - docker-dns
    # - geerlingguy.ntp

- hosts: getting
  become: true
  remote_user: joe
  roles:
#    - geerlingguy.docker
#    - docker-sonarr
#    - docker-radarr
    - docker-transmission
#    - docker-jackett
