---
# - hosts: all
- hosts: v-docker03.telaranrhiod.space
  become: true
  remote_user: joe
  roles:
    - basic-server
    - zsh
    - geerlingguy.pip
    - geerlingguy.docker
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/setup.vault

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    - docker-unifi
    - docker-uptime-kuma
    - docker-dashy
    - docker-smokeping
    # - {
        # role: docker-piHole,
        # pihole_virtual_hostname: "pihole01",
        # pihole_virtual_host: "pihole01.telaranrhiod.space",
      # }
    # - docker-librespeed
    - docker-vaultwarden
    # - docker-piHole-Influx
    - docker-grafana
    - docker-jackett
    # - docker-minecraft
    - docker-swag
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/main.vault

- hosts: getting
  become: true
  remote_user: ansible
  roles:
    # - {
    #   role: docker-piHole,
    #   pihole_virtual_hostname: "pihole02",
    #   pihole_virtual_host: "pihole02.telaranrhiod.space",
    # }
    - docker-jackett
    - docker-overseerr
    - docker-sonarr
    - docker-radarr
    - docker-signal-messager
#     - docker-piHole-Influx
#     - docker-tautlli
#     - docker-varken
    - docker-swag
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/main.vault

- hosts: torrents
  become: true
  remote_user: ansible
  roles:
    - docker-swag
  tags:
    - torrents
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/main.vault