---
# - name: Setup the servers basic
#   hosts: all
#   become: true
#   remote_user: joe
#   roles:
#     # - geerlingguy.docker
#     - basic-server
#     # - zsh
#     # - geerlingguy.pip
#     # - role: docker-common
#     #   tags: [setup, docker-common]
#   vars_files:
#     - vars/main.vault.yml
#     - vars/setup.vault.yml
#     - vars/main.yml
#   vars:
#     ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
#   tags:
#     setup

- hosts: pihole.mcharryville.space
  become: true
  remote_user: ansible
  roles:
    - role: docker-swag
      tags: [ setup, proxy, docker-swag ]
    - role: docker-piHole
      vars:
        pihole_virtual_hostname: "pihole"
        pihole_virtual_host: "pihole.mcharryville.space"
      tags: [ pihole, dns ]
  vars:
    ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    # - role: docker-semaphore
    #   tags: [ semaphore, docker-semaphore ]
    # - role: findarato.docker-semaphore
    #   tags: [ semaphore, docker-semaphore ]
    # - role: docker-dashy
    #   tags: [ dashy ]
    - docker-unifi
    - docker-uptime-kuma
    - docker-smokeping
    # Moved away from this to prowlarr
    # - docker-jackett
    # - docker-prowlarr
    # - docker-overseerr
    # - docker-sonarr
    # - docker-radarr
    # - docker-lidarr
    - docker-vaultwarden
    # - docker-grafana
    # - docker-syncthing
    # - docker-minecraft
    # - role: docker-swag
    #   tags: [ setup, proxy ]
  vars:
    ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

# - hosts: torrents
#   become: true
#   remote_user: ansible
#   roles:
#     - role: docker-swag
#       tags: [ setup, proxy, docker-swag ]
#     - role: docker-deluge
#       tags: [ deluge, docker-deluge]
#   tags:
#     - torrents
#   vars:
#     ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
#   vars_files:
#     - vars/main.vault.yml
#     - vars/main.yml