---
# - name: Setup the servers basic
#   hosts: all
#   become: true
#   remote_user: ansible
#   roles:
#     - basic-server
#     # - zsh
#     # - geerlingguy.pip
#     - role: docker-common
#       tags: [setup, docker-common]
#   vars_files:
#     - vars/main.vault.yml
#     - vars/setup.vault.yml
#     - vars/main.yml
#   tags:
#     setup

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    # - role: docker-dashy
    #   tags: [ dashy ]
    # - role: docker-homepage
    #   tags: [ homepage ]
    - role: docker-audiobookshelf
      tags: [ audiobookshelf ]

    # - role: docker-apt-cacher-ng
    #   tags: [ apt-cacher-ng ]
    - role: docker-piHole
      tags: [ pihole ]
    # - role: docker-changedetection
    #   tags: [ changedetection ]
    # - role: docker-discountbandit
    #   tags: [ discountbandit ]
    - role: docker-gatus
      tags: [ gatus ]
    - role: docker-unifi
      tags: [ unifi ]
    - role: docker-uptime-kuma
      tags: [ uptime-kuma, monitoring ]
    # - role: docker-smokeping
    #   tags: [ smokeping, monitoring ]
    - role: docker-vaultwarden
      tags: [ vaultwarden, docker-vaultwarden ]
    - role: docker-grafana
      tags: [ grafana, docker-grafana ]
    # - docker-syncthing
    # - docker-minecraft
    - role: docker-swag
      tags: [ setup, proxy ]
  vars:
    ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
    using_swag: true
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

- hosts: pirate
  become: true
  remote_user: ansible
  roles:
    - role: docker-telegraf
      tags: [ setup, proxy ]
    - role: arr/docker-deluge
      tags: [ deluge, torrent, arr ]
    - role: arr/docker-prowlarr
      tags: [ prowlarr, arr ]
    - role: arr/docker-overseerr
      tags: [ overseerr, arr ]
    - role: arr/docker-sonarr
      tags: [ sonarr,arr ]
    - role: arr/docker-radarr
      tags: [ radarr,arr ]
    - role: arr/docker-lidarr
      tags: [ lidarr,arr ]
  post_tasks:
    - name: clean up temp ansible
      ansible.builtin.file:
        path: /tmp/ansible
        state: absent
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
    - arr_docker_network: "tortuga"
  vars_files:
    - vars/main.yml
    - vars/main.vault.yml

# - hosts: torrents
#   become: true
#   remote_user: ansible
#   roles:
#     - role: docker-swag
#       tags: [ setup, proxy, docker-swag ]
#     - role: docker-deluge
#       tags: [ deluge, docker-deluge ]
#   tags:
#     - torrents
#   vars:
#     ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
#   vars_files:
#     - vars/main.vault.yml
#     - vars/main.yml

# - hosts: docker-cluster
#   become: true
#   remote_user: ansible
#   roles:
#     - geerlingguy.docker
#     - role: docker-swag
#       tags: [ setup, proxy, docker-swag ]
#     - role: docker-speedtest-tracker
#       tags: [ speedtest-tracker ]
#     - role: docker-unifi
#       tags: [ unifi ]
#     - role: docker-uptime-kuma
#       tags: [ uptime-kuma, monitoring ]
#   tags:
#     - v-docker04
#   vars_files:
#     - vars/main.vault.yml
#     - vars/main.yml