---
# - hosts: all
# - hosts: v-docker03.telaranrhiod.space
#   become: true
#   remote_user: joe
#   roles:
#     - basic-server
#     - zsh
#     - geerlingguy.pip
#     - geerlingguy.docker
#   vars_files:
#     - vars/main.vault.yml
#     - vars/setup.vault
#     - vars/main.yml

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    - docker-dashy
    - docker-unifi
    - docker-uptime-kuma
    - docker-smokeping
    - docker-jackett
    - docker-overseerr
    - docker-sonarr
    - docker-radarr
    - {
        role: docker-piHole,
        pihole_virtual_hostname: "pihole",
        pihole_virtual_host: "pihole.telaranrhiod.space",
      }
    - docker-vaultwarden
    - docker-grafana
    - docker-syncthing
    # - docker-minecraft
    - docker-swag
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

- hosts: getting
  become: true
  remote_user: ansible
  roles:
    # - {
    #   role: docker-piHole,
    #   pihole_virtual_hostname: "pihole02",
    #   pihole_virtual_host: "pihole02.telaranrhiod.space",
    # }

#     - docker-signal-messager
# #     - docker-piHole-Influx
# #     - docker-tautlli
# #     - docker-varken
#     - docker-swag
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

- hosts: torrents
  become: true
  remote_user: ansible
  roles:
    - docker-swag
  tags:
    - torrents
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml