---
# - hosts: all
- name: Setup the servers basic
  hosts: v-docker03.telaranrhiod.space,torrents
  become: true
  remote_user: joe
  roles:
    # - basic-server
    # - zsh
    # - geerlingguy.pip
    # - geerlingguy.docker
    - role: docker-common
      tags: [setup, docker-common]
  vars_files:
    - vars/main.vault.yml
    - vars/setup.vault
    - vars/main.yml

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    - role: findarato.docker-semaphore
      tags: [ semaphore, docker-semaphore ]
    - role: docker-dashy
      tags: [ dashy ]
    - docker-unifi
    - docker-uptime-kuma
    - docker-smokeping
    - docker-jackett
    - docker-overseerr
    - docker-sonarr
    - docker-radarr
    - role: docker-piHole
      vars:
        pihole_virtual_hostname: "pihole"
        pihole_virtual_host: "pihole.telaranrhiod.space"
      tags: [ pihole, dns ]

    - docker-vaultwarden
    - docker-grafana
    - docker-syncthing
    # - docker-minecraft
    - role: docker-swag
      tags: [ setup, proxy ]

  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

# - hosts: getting
#   become: true
#   remote_user: ansible
#   roles:
#     # - {
#     #   role: docker-piHole,
#     #   pihole_virtual_hostname: "pihole02",
#     #   pihole_virtual_host: "pihole02.telaranrhiod.space",
#     # }

# #     - docker-signal-messager
# # #     - docker-piHole-Influx
# # #     - docker-tautlli
# # #     - docker-varken
#     # - role: docker-swag
#     #   tags: [ setup, proxy ]
#   vars_files:
#     - vars/main.vault.yml
#     - vars/main.yml

- hosts: torrents
  become: true
  remote_user: ansible
  roles:
    - role: docker-swag
      tags: [ setup, proxy, docker-swag ]
    - role: docker-deluge
      tags: [ deluge, docker-deluge]
  tags:
    - torrents
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml