---
# - name: Setup the servers basic
#   hosts: all
#   become: true
#   remote_user: joe
#   roles:
#     # - geerlingguy.docker
#     - basic-server
#     # - zsh
#     # - geerlingguy.pip
#     # - role: docker-common
#     #   tags: [setup, docker-common]
#   vars_files:
#     - vars/main.vault.yml
#     - vars/setup.vault.yml
#     - vars/main.yml
#   vars:
#     ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
#   tags:
#     setup

- hosts: watching
  become: true
  remote_user: ansible
  roles:
    # - role: docker-semaphore
    #   tags: [ semaphore, docker-semaphore ]
    # - role: findarato.docker-semaphore
    #   tags: [ semaphore, docker-semaphore ]
    - role: docker-dashy
      tags: [ dashy ]
    - role: docker-homepage
      tags: [ homepage ]
    - role: docker-audiobookshelf
      tags: [ audiobookshelf ]
    - role: docker-speedtest-tracker
      tags: [ speedtest-tracker ]
    # - role: docker-apt-cacher-ng
    #   tags: [ apt-cacher-ng ]
    - role: docker-piHole
      tags: [ pihole ]
    # - role: docker-changedetection
    #   tags: [ changedetection ]
    # - role: docker-discountbandit
    #   tags: [ discountbandit ]
    # - docker-gatus
    - role: docker-unifi
      tags: [ unifi ]
    - role: docker-uptime-kuma
      tags: [ uptime-kuma, monitoring ]
    - role: docker-smokeping
      tags: [ smokeping, monitoring ]
    - role: docker-prowlarr
      tags: [ prowlarr, arr ]
    - role: docker-overseerr
      tags: [ overseerr, arr ]
    - role: docker-sonarr
      tags: [ sonarr,arr ]
    - role: docker-radarr
      tags: [ radarr,arr ]
    - role: docker-lidarr
      tags: [ lidarr,arr ]
    - docker-vaultwarden
    - docker-grafana
    # - docker-syncthing
    # - docker-minecraft
    - role: docker-swag
      tags: [ setup, proxy ]
  vars:
    ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
    using_swag: true
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml

# - hosts: torrents
#   become: true
#   remote_user: ansible
#   roles:
#     - role: docker-swag
#       tags: [ setup, proxy, docker-swag ]
#     - role: docker-deluge
#       tags: [ deluge, docker-deluge]
#   tags:
#     - torrents
#   vars:
#     ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
#   vars_files:
#     - vars/main.vault.yml
#     - vars/main.yml

# - hosts: v-docker04.mcharryville.space
#   become: true
#   remote_user: root
#   roles:
#     - role: docker-minecraft
#       tags: [ minecraft]
#   tags:
#     - minecraft
#   vars:
#     ansible_become_pass: "{{ vault_ansible_remote_user_password }}"
#   vars_files:
#     - vars/main.vault.yml
#     - vars/main.yml