---
# Apply common configuration to all hosts
# - hosts: all
#   become: true
#   remote_user: joe
#   roles:
#     - basic-server
#     - zsh
#     - geerlingguy.repo-epel
#     - geerlingguy.pip
#     - geerlingguy.docker
#     - docker-watchtower
#   vars_files:
#     - vars/main.yml
#     - vars/vault

- hosts: watching
  become: true
  remote_user: joe
  roles:
    - docker-proxy
    - {
        role: docker-piHole,
        pihole_virtual_hostname: "pihole01",
        pihole_virtual_host: "pihole01.telaranrhiod.space",
      }
    # - docker-piHole-Influx
    - docker-grafana
    - docker-jackett
    # - docker-prometheus
    # - docker-tautlli
    #  - docker-sonarr
    #  - docker-varken
  vars_files:
    - vars/main.yml
    - vars/vault

- hosts: getting
  become: true
  remote_user: joe
  roles:
    - docker-proxy
    - {
        role: docker-piHole,
        pihole_virtual_hostname: "pihole02",
        pihole_virtual_host: "pihole02.telaranrhiod.space",
      }
      # - docker-piHole-Influx
      # - docker-grafana
      # - docker-jackett
    #  - docker-tautlli
    - docker-sonarr
    #  - docker-varken
  vars_files:
    - vars/main.yml
    - vars/vault

# - hosts: pi-getting
#   become: true
#   remote_user: pi
#   roles:
#     - geerlingguy.docker
#     - docker-transmission
#   vars_files:
#     - vars/main.yml
#     - vars/vault
