all:
  children:
    docker_cluster:
      hosts:
        wpl-monitor02:
        wpl-docker01.vm:
        wpl-docker02.vm:
        wpl-docker03.vm:
        wpl-docker04.vm:
    logs:
      hosts:
        #wpl-docker01.vm:
        #wpl-docker02.vm:
        #wpl-docker03.vm:
        #wpl-docker04.vm:
    grafana:
      hosts:
        wpl-docker01.vm:
    LibreNMS:
      hosts:
        wpl-docker03.vm:
    influxdb:
      hosts:
        wpl-docker02.vm:
        wpl-docker03.vm:
    home:
      children:
        monitoring:
          hosts:
            stats.wheel:
        plex:
          hosts:
            tarabon.wheel:
        influxdb:
          hosts:
            stats.wheel: