---
- hosts: rpi:new_rpi
  become: true
  roles:
    - geerlingguy.pip
    # - geerlingguy.docker
    # - docker-swag
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault
  tags:
    - rpi

# - hosts: piBlocks
#   become: true
#   remote_user: pi
#   roles:
#     - docker-piHole
#   vars:
#     - ansible_python_interpreter: "/usr/bin/python3"
#   vars_files:
#     - vars/main.yml
#     - vars/vault
#   tags:
#     - rpi

# - hosts: rpi-docker01.telaranrhiod.space
#   become: true
#   remote_user: pi
#   roles:
#     - docker-uptime-kuma
#   vars:
#     - ansible_python_interpreter: "/usr/bin/python3"
#   vars_files:
#     - vars/main.yml
#     - vars/vault
#   tags:
#     - rpi

- hosts: rpi-docker02.telaranrhiod.space
  become: true
  remote_user: joe
  roles:
    # - docker-pi-alert
    # - docker-dashy
    # - docker-jackett
    # - docker-signal-messager
    - docker-swag
    - docker-piHole
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault
  tags:
    - rpi

- hosts: rpi-docker03.telaranrhiod.space
  become: true
  remote_user: pi
  roles:
    - docker-swag
    - docker-piHole
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault
  tags:
    - rpi
