---
# - hosts: rpi-docker02.telaranrhiod.space
# # - hosts: rpi:new_rpi
#   become: true
#   tasks:
#     - name: Make sure python is ready
#       package:
#         state: present
#         name: python3-venv
#   roles:
#     # - geerlingguy.pip
#     # - gregnrobinson.blinkstick
#     - role: geerlingguy.docker
#       docker_edition: 'ce'
#       docker_packages:
#         - "docker-{{ docker_edition }}"
#         - "docker-{{ docker_edition }}-cli"
#         - "docker-{{ docker_edition }}-rootless-extras"
#         - "containerd.io"
#       docker_users:
#         - joe
#     # - docker-swag
#   vars_files:
#     - vars/main.yml
#     - vars/main.vault.yml
#   tags:
#     - rpi

- hosts: piBlocks
  become: true
  remote_user: pi
  roles:
    - docker-piHole
    - docker-swag
  vars_files:
    - vars/main.yml
    - vars/main.vault.yml
  tags:
    - rpi

# - hosts: rpi-docker01.telaranrhiod.space
#   become: true
#   remote_user: pi
#   roles:
#     - docker-uptime-kuma
#   vars_files:
#     - vars/main.yml
#     - vars/main.vault.yml
#   tags:
#     - rpi

- hosts: rpi-docker02.telaranrhiod.space
  become: true
  remote_user: joe
  roles:
    # - docker-signal-messager
    # - docker-swag
    # - docker-piHole
  vars_files:
    - vars/main.yml
    - vars/main.vault.yml
  tags:
    - rpi

- hosts: rpi-docker03.telaranrhiod.space
  become: true
  remote_user: pi
  roles:
    # - docker-swag
    # - docker-piHole
  vars_files:
    - vars/main.yml
    - vars/main.vault.yml
  tags:
    - rpi
