---
# - hosts: rpi
#   become: true
#   remote_user: pi
#   roles:
#     # - acimadamore.raspberry_pi
#   vars:
#     - ansible_python_interpreter: "/usr/bin/python3"
#   vars_files:
#     - vars/main.yml
#     - vars/vault
#   tags:
#     - rpi

- hosts: piBlocks
  become: true
  remote_user: pi
  roles:
    # - docker-proxy
    - docker-piHole
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - vars/main.yml
    - vars/vault
  tags:
    - rpi

# - hosts: rpi-docker01.telaranrhiod.space
#   become: true
#   remote_user: pi
#   roles:
#     - docker-uptime-kuma
#   vars:
#     - ansible_python_interpreter: "/usr/bin/python3"
#   vars_files:
#     - vars/main.yml
#     - vars/vault
#   tags:
#     - rpi