---
# Apply common configuration to all hosts
- hosts: all
  become: true
  remote_user: it
  roles:
    - basic-server
    - zsh

- hosts: docker-cluster
  become: true
  remote_user: it
  roles:
    - docker-common
    - docker-dns

#
- hosts: grafana
  remote_user: it
  become: true
  roles:
    - docker-grafana

- hosts: plex
  remote_user: it
  become: true
  roles:
    - docker-plex
#
- hosts: influxdb
  remote_user: it
  become: true
  roles:
    - docker-influxDB

- hosts: LibreNMS
  remote_user: it
  become: true
  roles:
    - { role: docker-LibreNMS, tags: 'libreNMS'}