---
- hosts: vps
  become: true
  gather_facts: true
  remote_user: root
  pre_tasks:
    - name: install pip
      package:
        name: "{{ package_name }}"
        state: latest
      loop:
        - python3-pip
        - python3-docker
      loop_control:
        loop_var: 'package_name'
  roles:
    - role: docker-npm
      tags: [ npm ]
    - docker-uptime-kuma
    - docker-ntfy
    - docker-website
    - role: docker-whoami
      tags: [ whoami ]
    - role: docker-xmrigproxy
      tags: [ xmrigproxy ]
    # - role: artis3n.tailscale
    #   tags: [ tailscale ]
    #   vars:
    #     tailscale_up_skip: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    using_swag: false
  vars_files:
    - vars/main.yml
    - vars/main.vault.yml