- name: Create Docker paths
  file:
    path: "/docker/containers/varken/{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - config

- name: Recreate varken container
  docker_container:
    name: varken
    image: boerderij/varken:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8181"
    published_ports:
      - 8181:8181
    volumes:
      - /docker/containers/varken/config:/config
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "varken.telaranrhiod.space"
      VRKN_GLOBAL_SONARR_SERVER_IDS: 1
      VRKN_GLOBAL_RADARR_SERVER_IDS: false
      VRKN_GLOBAL_LIDARR_SERVER_IDS: false
      VRKN_GLOBAL_TAUTULLI_SERVER_IDS: 1
      # VRKN_GLOBAL_OMBI_SERVER_IDS: 1
      # VRKN_GLOBAL_SICKCHILL_SERVER_IDS: false
      VRKN_GLOBAL_UNIFI_SERVER_IDS: false
      # VRKN_GLOBAL_MAXMIND_LICENSE_KEY: xxxxxxxxxxxxxxxx
      VRKN_INFLUXDB_URL: influx.telaranrhiod.space
      VRKN_INFLUXDB_PORT: 8086
      VRKN_INFLUXDB_SSL: false
      VRKN_INFLUXDB_VERIFY_SSL: false
      VRKN_INFLUXDB_USERNAME: root
      VRKN_INFLUXDB_PASSWORD: root
      VRKN_TAUTULLI_1_URL: tautulli.telaranrhiod.space
      VRKN_TAUTULLI_1_APIKEY: 71414d75d67b41f19bae9f25ea1126ed
      VRKN_TAUTULLI_1_SSL: false
      VRKN_TAUTULLI_1_VERIFY_SSL: false
      VRKN_TAUTULLI_1_GET_ACTIVITY: true
      VRKN_TAUTULLI_1_GET_ACTIVITY_RUN_SECONDS: 30
      VRKN_TAUTULLI_1_GET_STATS: true
      VRKN_TAUTULLI_1_GET_STATS_RUN_SECONDS: 3600
      VRKN_SONARR_1_URL: sonarr.telaranrhiod.space
      VRKN_SONARR_1_APIKEY: 86ae0d2c11c84bb89b7e8cf3aa07873c
      VRKN_SONARR_1_SSL: false
      VRKN_SONARR_1_VERIFY_SSL: false
      VRKN_SONARR_1_MISSING_DAYS: 7
      VRKN_SONARR_1_MISSING_DAYS_RUN_SECONDS: 300
      VRKN_SONARR_1_FUTURE_DAYS: 1
      VRKN_SONARR_1_FUTURE_DAYS_RUN_SECONDS: 300
      VRKN_SONARR_1_QUEUE: true
      VRKN_SONARR_1_QUEUE_RUN_SECONDS: 300
      # VRKN_RADARR_1_URL: radarr1.domain.tld
      # VRKN_RADARR_1_APIKEY: xxxxxxxxxxxxxxxx
      # VRKN_RADARR_1_SSL: false
      # VRKN_RADARR_1_VERIFY_SSL: false
      # VRKN_RADARR_1_QUEUE: true
      # VRKN_RADARR_1_QUEUE_RUN_SECONDS: 300
      # VRKN_RADARR_1_GET_MISSING: true
      # VRKN_RADARR_1_GET_MISSING_RUN_SECONDS: 300
      # VRKN_LIDARR_1_URL: lidarr1.domain.tld:8686
      # VRKN_LIDARR_1_APIKEY: xxxxxxxxxxxxxxxx
      # VRKN_LIDARR_1_SSL: false
      # VRKN_LIDARR_1_VERIFY_SSL: false
      # VRKN_LIDARR_1_MISSING_DAYS: 30
      # VRKN_LIDARR_1_MISSING_DAYS_RUN_SECONDS: 300
      # VRKN_LIDARR_1_FUTURE_DAYS: 30
      # VRKN_LIDARR_1_FUTURE_DAYS_RUN_SECONDS: 300
      # VRKN_LIDARR_1_QUEUE: true
      # VRKN_LIDARR_1_QUEUE_RUN_SECONDS: 300
      # VRKN_OMBI_1_URL: ombi.domain.tld
      # VRKN_OMBI_1_APIKEY: xxxxxxxxxxxxxxxx
      # VRKN_OMBI_1_SSL: false
      # VRKN_OMBI_1_VERIFY_SSL: false
      # VRKN_OMBI_1_GET_REQUEST_TYPE_COUNTS: true
      # VRKN_OMBI_1_REQUEST_TYPE_RUN_SECONDS: 300
      # VRKN_OMBI_1_GET_REQUEST_TOTAL_COUNTS: true
      # VRKN_OMBI_1_REQUEST_TOTAL_RUN_SECONDS: 300
      # VRKN_OMBI_1_GET_ISSUE_STATUS_COUNTS: true
      # VRKN_OMBI_1_ISSUE_STATUS_RUN_SECONDS: 300
      # VRKN_SICKCHILL_1_URL: sickchill.domain.tld:8081
      # VRKN_SICKCHILL_1_APIKEY: xxxxxxxxxxxxxxxx
      # VRKN_SICKCHILL_1_SSL: false
      # VRKN_SICKCHILL_1_VERIFY_SSL: false
      # VRKN_SICKCHILL_1_GET_MISSING: true
      # VRKN_SICKCHILL_1_GET_MISSING_RUN_SECONDS: 300