---
- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    state: 'directory'
    owner: 'docker'
    group: 'docker'
    mode: '0755'
  loop:
    - 'janitor_data'
  loop_control:
    loop_var: 'dir'
  tags: janitor

- name: 'Place files for Janitor'
  ansible.builtin.copy:
    src: 'clean_docker.sh'
    dest: "{{ docker_data_dir }}/janitor_data/clean_docker.sh"
    owner: 'docker'
    group: 'docker'
    mode: '0755'
  tags: janitor

- name: 'Deploy Docker Janitor'
  community.docker.docker_container:
    name: 'janitor'
    command: '/clean_docker.sh'
    image: 'docker'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - "{{ docker_data_dir }}/janitor_data/clean_docker.sh:/clean_docker.sh:ro"
    restart_policy: unless-stopped
    user: null
  tags: janitor