---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Add lidarr to Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
  tags:
    - lidarr
    - arr

- name: Create Docker paths
  file:
    path: "{{ docker_data_dir }}/{{ item }}"
    state: directory
    mode: "0775"
    owner: "1000"
    group: docker
  with_items:
    - downloads
    - config

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_downloads_mount.type }}"
      o: "{{ vault_arr_downloads_mount.opts }}"
      device: "{{ vault_arr_downloads_mount.device }}"
  tags:
    - deluge
    - arr

- name: 🎥 Create NFS mount Music
  community.docker.docker_volume:
    name: nfs-music
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_music_mount.type }}"
      o: "{{ vault_arr_music_mount.opts }}"
      device: "{{ vault_arr_music_mount.device }}"
  tags:
    - radarr
    - arr


- name: Recreate lidarr container
  community.docker.docker_container:
    name: lidarr
    image: lscr.io/linuxserver/lidarr
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8686'
    volumes:
      - /mnt/storage/Music/download:/music
      - "{{ docker_lidarr_storage }}/config:/config"
      - /mnt/storage/Music/download:/music
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: theways
      - name: "{{ traefik_proxy_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.rule: Host(`{{ lidarr_app_name }}.{{ traefik_arr_domain }}`)
      traefik.http.routers.lidarr.tls: "true"
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.services.lidarr.loadbalancer.server.port: "8686"
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - lidarr