---
# tasks file for docker-minecraft
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/librespeed/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
  with_items:
    - config

- name: Recreate librespeed container
  community.docker.docker_container:
    name: librespeed
    image: ghcr.io/linuxserver/librespeed
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      # - '443'
      - '80'
    # ports:
    #   - '8888:80'
    volumes:
      - /docker/containers/librespeed/config:/config
    networks:
      - name: theways
    networks_cli_compatible: false
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      DB_TYPE: "mysql"
      DB_NAME: "librespeed"
      DB_HOSTNAME: "10.1.1.5"
      DB_USERNAME: "librespeed"
      DB_PASSWORD: "{{vault_docker_librespeed_mysql_password}}"
      DB_PORT: "3306"
  tags:
    - librespeed

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/librespeed.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/librespeed.subdomain.conf"
    mode: '0440'
  tags:
    - librespeed
    - SWAG