---

include_vars:            vault
remote_user:             pi
ansible_become_pass:     "{{vault_user_pass}}"
pip_package:             python3-pip

# PIHole variables
docker_pihole_virtual_hostname: "pihole02"
docker_pihole_virtual_host:     "pihole02.telaranrhiod.space"
docker_piHole_storage:          "/docker/containers/pihole/"

# Basic setup vars
raspberry_pi_locale:            en_US.UTF-8
raspberry_pi_timezone:          America/Chicago
raspberry_pi_keyboard_layout:   en
# raspberry_pi_hostname:          rpi-docker03
raspberry_pi_configure_network: no
# raspberry_pi_ip_address:      192.168.0.2/24
# raspberry_pi_routers:         192.168.0.1
# raspberry_pi_dns_servers:     [1.1.1.1, 1.0.0.1]
# raspberry_pi_use_wifi:        true
# raspberry_pi_wifi_country:    AR
# raspberry_pi_wifi_ssid:       myHomeWiFiNetwork
# raspberry_pi_wifi_password:   someWifiPassword
raspberry_pi_packages:
  - git
raspberry_pi_config_options:
  # - option: dtoverlay
  #   value: gpio-ir,gpio_pin=10
  # - option: dtoverlay
  #   regexp: dtoverlay=vc4-kms-v3d
  #   value: vc5-kms-v4d
  # - option: otg_mode
  #   value: 2