---
# tasks file for docker-transmission

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: "{{ docker_network }}"

- name: Create Docker paths
  file:
    path: "/docker/containers/transmission/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - data
    - config
    - data/watch
    - data/downloads
    - data/downloads/complete
  tags:
    - transmission
    # - data/downloads/incomplete

- name: Create and Update Transmission Container
  community.docker.docker_container:
    name: transmission
    image: linuxserver/transmission
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "9091"
      - "27975"
    published_ports:
      - 9091:9091
      - 27975:27975
      - 27975:27975/udp
    volumes:
      - "/docker/containers/transmission/data/downloads:/downloads"
      - "/docker/containers/transmission/data/watch:/watch"
      - "/docker/containers/transmission/config:/config"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Chicago"
      VIRTUAL_HOST: "transmission.telaranrhiod.space"
  tags:
    - transmission

- name: Open Ports for transmission firewallD
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
  when: ansible_distribution == "CentOS"
  tags:
    - transmission

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/transmission.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/transmission.subdomain.conf.sample"
    mode: '0440'
  tags:
    - transmission
    - SWAG