---
- name:       "Install epel for extra packages  {{ansible_os_family}}"
  yum:
    name:     "{{ item }}"
    state:    present
  with_items:
    - epel-release

- name:       "Install python bindings for SE Linux  {{ansible_os_family}}"
  yum:
    name:     "{{ item }}"
    state:    present
  with_items:
    - libselinux-python
    - libsemanage-python
    - python-pip