#!/usr/bin/env ansible-playbook
---

- name:               Clone dotfiles repos
  become:             false
  git:
    repo:             "https://github.com/Findarato/dotFiles.git"
    dest:             "/home/{{ local_user }}/src/dotFiles"
    accept_hostkey:   yes
    track_submodules: no
    update:           yes
    force:          yes
  register:           result
    # version:


- name:               Delete exsisting files in home directory
  become:             false
  file:
    src:              "/home/{{ local_user }}/src/dotFiles/{{ old_file }}"
    dest:             "/home/{{ local_user }}/{{ old_file }}"
    state:            absent
  with_items:
    - bin
    - .aliases
    - .ansible.cfg
    - .bashrc
    - .dircolors
    - .functions
    - .gitconfig
    - .gitignore
    - .gitmessage
    - .gitmodules
    - .powerlevel9k
    - .rainbow_config.json
    - .zprofile
    - .zshrc
  loop_control:
    loop_var:         old_file
  when:               result|changed

- name:               Link up Home directory to dotfiles
  become:             false
  file:
    src:              "/home/{{ local_user }}/src/dotFiles/{{ link_file }}"
    dest:             "/home/{{ local_user }}/{{ link_file }}"
    state:            link
  with_items:
    - bin
    - .aliases
    - .ansible.cfg
    - .bashrc
    - .dircolors
    - .functions
    - .gitconfig
    - .gitignore
    - .gitmessage
    - .gitmodules
    - .powerlevel9k
    - .rainbow_config.json
    - .zprofile
    - .zshrc
  loop_control:
    loop_var:         link_file
  when:               result|changed