- include: "{{ansible_os_family}}.yml"

- name: Ensure fail2ban pid directory exsists
  file:
    path: /var/run/fail2ban
    state: directory
    mode: 0755

- name: Start fail2ban
  systemd:
      name: fail2ban
      state: started
      enabled: yes
  tags: fail2ban, service
