---
- name:       Install EPEL
  yum:
    name:     epel-release
    state:    present


- name:       Install python bindings for SE Linux
  yum:
    name:     "{{ item }}"
    state:    present
  with_items:
    - libselinux-python
    - libsemanage-python
    - fail2ban-all
    - nano
    - wget

- name: "Install Docker helpers {{ansible_os_family}}"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip