---
- name:       Install EPEL
  yum:
    name:   "http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm"
    state:    present


- name:       Install python bindings for SE Linux
  yum:
    name:     "{{ item }}"
    state:    present
  with_items:
    - libselinux-python
    - libsemanage-python
    - fail2ban-all
    - nano
    - wget
    - python-pip