- name: Ensure sudo no password group exsists
  ansible.builtin.group:
    name: sudo_no_password
    state: present
    gid: 1000002

- name: Create ansible User
  user:
    name: ansible
    comment: Account for running remote UNIX commands
    uid: "1000001"
    createhome: yes        # Defaults to yes
    home: /home/ansible
    password: "{{ vault_ansible_password }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: "ed25519"
    groups:
      - "{{ sudo_group }}"
      - ansible

- name: Create Users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    state: present
    # local: yes
    shell: "{{ item.shell }}"
    createhome: "{{ item.createhome }}"
    home: "{{ item.home }}"
    password: "{{ vault_default_password }}"
    update_password: "{{ item.update_password }}"
    generate_ssh_key: "{{ item.generate_ssh_key }}"
    ssh_key_bits: "{{ item.ssh_key_bits }}"
    ssh_key_file: "{{ item.ssh_key_file }}"
    ssh_key_type: "{{ item.ssh_key_type }}"
    skeleton: /etc/skel/
  with_items:
    - "{{ default_users }}"
    - "{{ extra_users }}"
  loop_control:
    label: "{{ item.name  }}"

- name: Groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
  with_items:
    - "{{ default_users }}"
    - "{{ extra_users }}"
  loop_control:
    label: "{{ item.name  }}"