- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    gid: "{{ item.gid }}"
  with_items:
    - "{{ groups_to_make }}"

- name: Create ansible User
  ansible.builtin.user:
    name: ansible
    comment: Account for running Ansible
    uid: "1000001"
    createhome: yes        # Defaults to yes
    home: /home/ansible
    password: "{{ vault_ansible_user_password | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: "ed25519"
    update_password: "always"
    groups:
      - "{{ sudo_group }}"
      - ansible

- name: Create docker User
  ansible.builtin.user:
    name: dockerUser
    comment: Account for doing Docker things
    uid: "1000002"
    createhome: yes        # Defaults to yes
    home: /home/dockerUser
    password: "{{ docker_password | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: "ed25519"
    update_password: "on_create"
    groups: []

- name: Create Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    state: present
    # local: yes
    shell: "{{ item.shell }}"
    createhome: "{{ item.createhome }}"
    home: "{{ item.home }}"
    password: "{{ default_password | password_hash('sha512') }}"
    update_password: "{{ item.update_password }}"
    generate_ssh_key: "{{ item.generate_ssh_key }}"
    ssh_key_bits: "{{ item.ssh_key_bits }}"
    ssh_key_file: "{{ item.ssh_key_file }}"
    ssh_key_type: "{{ item.ssh_key_type }}"
    skeleton: /etc/skel/
    groups: "{{ item.groups }}"
  with_items:
    - "{{ default_users }}"
  loop_control:
    label: "{{ item.name  }}"

- name: Set authorized key for Important Accounts
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'files/'+item+'.pub') }}"
  with_items:
    - ansible
    - joe

- name: Set NEW authorized key for Important Accounts
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'files/'+item+'_ed25519.pub') }}"
  with_items:
    - joe