# - name: Ensure ansible group exsists
#   ansible.builtin.group:
#     name: ansible
#     state: present
#     gid: 1000001

# - name: Ensure sudo no password group exsists
#   ansible.builtin.group:
#     name: sudo_no_password
#     state: present
#     gid: 1000002

- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    gid: "{{ item.gid }}"
  with_items:
    - "{{ groups_to_make }}"

- name: Create ansible User
  user:
    name: ansible
    comment: Account for running remote UNIX commands
    uid: "1000001"
    createhome: yes        # Defaults to yes
    home: /home/ansible
    password: "{{ vault_ansible_password | password_hash('sha512','fe46ffed005467') }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: "ed25519"
    groups:
      - "{{ sudo_group }}"
      - ansible


- name: Create docker User
  user:
    name: dockerUser
    comment: Account for running remote UNIX commands
    uid: "1000002"
    createhome: yes        # Defaults to yes
    home: /home/dockerUser
    password: "{{ vault_docker_password | password_hash('sha512','fe46ffed005467') }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: "ed25519"
    groups: []

- name: Create Users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    state: present
    # local: yes
    shell: "{{ item.shell }}"
    createhome: "{{ item.createhome }}"
    home: "{{ item.home }}"
    password: "{{ vault_default_password | password_hash('sha512','fe46ffed005467') }}"
    update_password: "{{ item.update_password }}"
    generate_ssh_key: "{{ item.generate_ssh_key }}"
    ssh_key_bits: "{{ item.ssh_key_bits }}"
    ssh_key_file: "{{ item.ssh_key_file }}"
    ssh_key_type: "{{ item.ssh_key_type }}"
    skeleton: /etc/skel/
    groups: "{{ item.groups }}"
  with_items:
    - "{{ default_users }}"
  loop_control:
    label: "{{ item.name  }}"

- name: Set authorized key for Important Accounts
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'files/'+item+'.pub') }}"
  with_items:
    - ansible
    - joe

- name: Set NEW authorized key for Important Accounts
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'files/'+item+'_ed25519.pub') }}"
  with_items:
    - joe