---
# tasks file for docker-dns
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_unifi_storage }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - /config
  tags:
    - unifi

- name: Recreate Unifi container
  community.docker.docker_container:
    name: unifi-controller
    # image: jacobalberty/unifi:latest
    image: ghcr.io/linuxserver/unifi-controller
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8080"
      - "8443"
      - "3478/udp"
      - "10001/udp"
    published_ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "1900:1900/udp"
    volumes:
      - "{{ docker_unifi_storage }}/config:/config"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: America/Chicago
      PUID: "1000"
      PGID: "1000"
      # MEM_LIMIT: "1024M"
      # MEM_STARTUP: "2048M"
  tags:
    - unifi