---
# tasks file for docker-dns
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_unifi_storage }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - /data
    - /log
    - /cert
    - /init.d
  tags:
    - unifi

- name: Recreate Unifi container
  community.general.docker_container:
    name: unifi
    # image: jacobalberty/unifi:latest-5
    image: jacobalberty/unifi:6.0
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8080"
      - "8443"
      - "3478/udp"
      - "10001/udp"
    published_ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
    volumes:
      - "{{ docker_unifi_storage }}/data:/unifi/data"
      - "{{ docker_unifi_storage }}/log:/unifi/log"
      - "{{ docker_unifi_storage }}/cert:/unifi/cert"
      - "{{ docker_unifi_storage }}/init.d:/unifi/init.d"
    env:
      TZ: America/Chicago
  tags:
    - unifi