---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/syncthing/{{ item }}"
    state: directory
    # mode: 0775
    # group: docker
  with_items:
    - downloads
    - config

- name: Recreate syncthing container
  community.docker.docker_container:
    name: syncthing
    image: linuxserver/syncthing
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8989'
    volumes:
      - /etc/localtime:/ect/localtime:ro
    networks_cli_compatible: false
    networks:
      - name: theways
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - syncthing

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/syncthing.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/syncthing.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG