---
# tasks file for docker-prowlarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest
  tags:
    - prowlarr
    - arr

- name: Add prowlarr to Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
    labels:
      arr: "true"
  tags:
    - prowlarr
    - arr

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    owner: 'docker'
    group: 'docker'
    mode: '0750'
    state: 'directory'
  loop:
    - 'prowlarr_config'
  loop_control:
    loop_var: 'dir'
  tags:
    - prowlarr
    - arr

- name: Recreate prowlarr container
  community.docker.docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - "{{ docker_prowlarr_storage }}/prowlarr_config:/config"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
      - name: "{{ traefik_proxy_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.rule: Host(`{{ prowlarr_app_name }}.{{ traefik_arr_domain }}`)
      traefik.http.routers.prowlarr.tls: "true"
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - prowlarr
    - arr
