---
# tasks file for docker-overseerr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/overseerr/{{ item }}"
    state: directory
    mode: "0775"
    owner: "1000"
    group: docker
  with_items:
    - config

- name: Recreate overseerr container
  community.docker.docker_container:
    name: overseerr
    image: lscr.io/linuxserver/overseerr
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "5055"
    volumes:
      - /docker/containers/overseerr/config:/config
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: theways
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      VERSION: latest
  tags:
    - overseerr

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/overseerr.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/overseerr.subdomain.conf"
    mode: "0440"
  notify:
    - Restart SWAG
  tags:
    - overseerr
    - SWAG
