---
- name: Install EPEL {{ ansible_distribution }}
  package:
    name: epel-release
    state: present
  when:
    - ansible_distribution == 'CentOS'

- name: Update system
  yum:
    name: "*"
    state: latest

- name: Install generic packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - wget
    - git
