---
- name: Install EPEL {{ ansible_distribution }}
  package:
    name: epel-release
    state: present
  when:
    - ansible_distribution == 'CentOS'

- name: Remove Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xe-guest-utilities
  ignore_errors: true

- name: Install generic packages RHEL
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - wget
    - git
    - nfs-utils
    - rsync
    - tmux
    # - xe-guest-utilities-latest
    - python3-passlib
    - stow
  ignore_errors: true
  # notify:
  #   - Reboot Host
