---
- name: Install EPEL {{ ansible_distribution }}
  package:
    name: epel-release
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Remove Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xe-guest-utilities
  ignore_errors: true

- name: Install generic packages RHEL
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - wget
    - git
    - nfs-utils
    - rsync
    - tmux
    - stow
    - python3-packaging
    - python3-pip
    - open-vm-tools
  ignore_errors: true

- name: Start open-vm-tools
  service:
    name: vmtoolsd.service
    state: started
    enabled: true

- name: Start vgauthd.service
  service:
    name: vgauthd.service
    state: started
    enabled: true
