---
# tasks file for docker-influxDB

- name: Create paths
  file:
    path: "/docker/containers/influxdb/{{ item }}"
    state: directory
    mode: 0775
    group: docker
  with_items:
    - data
    - config

- name: Copy influxdb config file
  copy:
    src: influxdb.conf
    dest: /docker/containers/influxdb/influxdb.conf
    mode: 0644

- name: Start influxDB container {{inventory_hostname}}
  docker_container:
    name: influxdb
    image: influxdb
    state: started
    restart_policy: unless-stopped
    recreate: false
    restart: yes
    pull: true
    exposed_ports:
      - 8083
      - 8086
      - 8089
      - 2003
    published_ports:
      - 8083:8083
      - 8086:8086
      - 8089:8089
      - 2003:2003
      - 25826:25826/udp
    volumes:
      - /docker/containers/influxdb/data:/var/lib/influxdb/
      - /docker/containers/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    env:
      VIRTUAL_HOST: "{{inventory_hostname}}influx.library.wpl.lib.in.us"

- name: Open Ports for influxdb
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
