---
# defaults file for docker-transmission

docker_storage_path: "/docker/containers/"
docker_homepage_storage: "{{docker_storage_path}/tailscale"

tailscale_auth_key: "{{ vault_tailscale_auth_key }}"

docker_log_driver: "json-file"
docker_log_options:
  max-file: "3"   # number of files or file count
  max-size: "10m" # file size
