---

## Title: /arr/docker-deluge/tasks/main.yml
## Description: Deploy Deluge in a docker container
## Author: Joseph Harry <findarato@gmail.com>
## Copyright: Joseph Harry <findarato@gmail.com>
## Date: 2026-03-01 15:03:02
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.
## 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# tasks file for docker-deluge

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest
  tags:
    - deluge
    - arr

- name: Private Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
    internal: true
    labels:
      arr: "true"
  tags:
    - deluge
    - arr

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    owner: 'docker'
    group: 'docker'
    mode: '0750'
    state: 'directory'
  loop:
    - 'deluge_data'
    - 'deluge_config'
  loop_control:
    loop_var: 'dir'
  tags:
    - deluge
    - arr

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: "{{ vault_arr_downloads_mount.type }}"
      o: "{{ vault_arr_downloads_mount.opts }}"
      device: "{{ vault_arr_downloads_mount.device }}"
  tags:
    - deluge
    - arr


- name: Create and Update Deluge Container
  community.docker.docker_container:
    name: deluge
    image: "lscr.io/linuxserver/deluge:{{ deluge_version }}"
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    container_default_behavior: no_defaults
    volumes:
      - "{{ docker_data_dir }}/deluge_config:/config"
      - arr-downloads:/downloads
    labels:
      traefik.enable: "true"
      traefik.http.routers.deluge.rule: Host(`{{ deluge_app_name }}.{{ traefik_arr_domain }}`)
      traefik.http.routers.deluge.tls: "true"
      traefik.http.routers.deluge.entrypoints: websecure
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
    env:
      PGID: "1000002" #docker user
      PUID: "1000"
      TZ: "America/Chicago"
      DELUGE_LOGLEVEL: error
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    # dns_search_domains: "{{ dns_domains }}"
    # dns_servers: "{{ dns_servers }}"
    # network_mode: "container:gluetun"
    networks:
      - name: "{{ arr_network_name }}"
        aliases:
          - deluge.mcharryville.space
          - deluge.arr.mcharryville.space
          - deluge
      - name: traefik_proxy
        aliases:
          - deluge.mcharryville.space
  tags:
    - deluge
    - arr