---
# defaults file for docker-transmission
# General Docker variables
docker_log_driver: "json-file"
docker_log_options:
  max-file: "3"   # number of files or file count
  max-size: "10m" # file size

docker_storage: "/docker/"
docker_ports:
    - 3000/tcp
    - 9091/tcp
    - 27975/tcp
    - 27975/udp
docker_portsUFW:
    - 3000
    - 9091
    - 27975

docker_transmission_blacklist: "http://john.bitsurge.net/public/biglist.p2p.gz"
docker_transmission_blocklist_enabled: true
docker_transmission_folders:
    - download_dir: "/downloads/complete"
