---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  children:
    blink:
      hosts:
        rpi-docker01:
          ansible_host: rpi-docker01.telaranrhiod.space #raspberry pi os
          serial: BS036976-3.0
        rpi-docker02:
          ansible_host: rpi-docker01.telaranrhiod.space #raspberry pi os
          serial: BS036976-3.0
        rpi-docker03:
          ansible_host: rpi-docker01.telaranrhiod.space #raspberry pi os
          serial: BS036976-3.0
    rpi:
      hosts:
        rpi-docker01.telaranrhiod.space: #raspberry pi os
        rpi-docker03.telaranrhiod.space: #raspberry pi os
      vars:
        ansible_user: pi
        ansible_python_interpreter: "/usr/bin/python3"
    new_rpi:
      hosts:
        rpi-docker02.telaranrhiod.space: #raspberry pi os
      vars:
        ansible_user: joe
        ansible_python_interpreter: "/usr/bin/python3"
    piGetting:
      hosts:
        rpi-docker01.telaranrhiod.space: #raspberry pi os
        rpi-docker02.telaranrhiod.space: #raspberry pi os
        rpi-docker03.telaranrhiod.space: #raspberry pi os
    piBlocks:
      hosts:
        rpi-docker02.telaranrhiod.space: #raspberry pi os
        rpi-docker03.telaranrhiod.space: #raspberry pi os
    getting:
      hosts:
        v-docker03.telaranrhiod.space: # Rocky Linux 8
    watching:
      hosts:
        v-docker03.telaranrhiod.space: # Rocky Linux 8
    stats:
      hosts:
        v-docker03.telaranrhiod.space: # Rocky Linux 8
    torrents:
      hosts:
        v-torrents.telaranrhiod.space: #