---
all:
  children:
    servers:
      hosts:
        v-docker02.telaranrhiod.space: #CentOS 7 Template
        v-docker01.telaranrhiod.space: #CentOS 7 Template
    getting:
      hosts:
        v-docker02.telaranrhiod.space: #CentOS 7 Template
    watching:
      hosts:
        v-docker01.telaranrhiod.space: #CentOS 7 Template
    stats:
      hosts:
        stats.telaranrhiod.space:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: joe
