---
all:
  children:
    getting:
      hosts:
        v-docker03.mcharryville.space: # Rocky Linux 8
    watching:
      hosts:
        v-docker03.mcharryville.space: # Rocky Linux 8
    docker-cluster:
      hosts:
        v-docker04.mcharryville.space: # Rocky Linux 10
          vars:
            proxmox: true
    minecraft:
      hosts:
        v-docker04.mcharryville.space: # Rocky Linux 10
          vars:
            proxmox: true
    stats:
      hosts:
        v-docker03.mcharryville.space: # Rocky Linux 8
    torrents:
      hosts:
        # v-torrents.mcharryville.space: #
        v-torrents.mcharryville.space: #
        pirate.mcharryville.space: #
          vars:
            proxmox: true
      vars:
        ansible_python_interpreter: "/usr/bin/python3"