---
all:
  children:
    rpi:
      hosts:
         rpi-docker01.telaranrhiod.space: #raspberry pi os
         rpi-docker02.telaranrhiod.space: #raspberry pi os
         rpi-docker03.telaranrhiod.space: #raspberry pi os
    piGetting:
      hosts:
         rpi-docker01.telaranrhiod.space: #raspberry pi os
         rpi-docker02.telaranrhiod.space: #raspberry pi os
         rpi-docker03.telaranrhiod.space: #raspberry pi os
    piBlocks:
      hosts:
         rpi-docker02.telaranrhiod.space: #raspberry pi os
         rpi-docker03.telaranrhiod.space: #raspberry pi os
    getting:
      hosts:
        v-docker02.telaranrhiod.space: #CentOS 7
    watching:
      hosts:
        v-docker01.telaranrhiod.space: #CentOS 7
        # 10.1.1.171: #CentOS 7
    stats:
      hosts:
        stats.telaranrhiod.space: # CentOS 7
        # v-stats.telaranrhiod.space: # CentOS 8
    torrents:
      hosts:
        torrents.telaranrhiod.space: # Fedora Servers
