---
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{docker_proxy_storage}}{{ item }}"
    state: directory
    mode: "0775"
    group: "1000"
    owner: "1000"
  with_items:
    - data
    - letsencrypt

- name: Create Nginx Proxy Manager
  community.docker.docker_container:
    name: proxy
    image: jc21/nginx-proxy-manager:latest
    state: started
    restart_policy: unless-stopped
    recreate: true
    pull: true
    ports:
      - "80:80/tcp"
      - "81:81/tcp"
      - "443:443/tcp"
    volumes:
      - "{{docker_proxy_storage}}/data:/data"
      - "{{docker_proxy_storage}}/letsencrypt:/etc/letsencrypt"
    networks_cli_compatible: false
    networks:
      - name: theways
    #   - name: container:tailscale-ha
    # env:
