---
# tasks file for docker-dns
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_signal_storage }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - /signal-cli-config
  tags:
    - signal-messager



- name: Recreate signal-messager container
  community.docker.docker_container:
    name: signal-messager
    image: bbernhard/signal-cli-rest-api:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8080"
    published_ports:
      - "8080:8080"
    volumes:
      - "{{ docker_signal_storage }}/signal-cli-config:/home/.local/share/signal-cli"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: America/Chicago
  tags:
    - signal-messager