---
# tasks file for docker-piHole

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Recreate pihole InfluxDB container
  community.docker.docker_container:
    name: pihole-influxDB
    image: registry.gitlab.com/janw/pi-hole-influx
    state: started
    restart_policy: always
    recreate: yes
    restart: yes
    pull: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env:
      PIHOLE_INFLUXDB_HOST: "influx.telaranrhiod.space"
      PIHOLE_INFLUXDB_PORT: "8086"
      PIHOLE_INFLUXDB_DATABASE: "pihole"
      PIHOLE_INSTANCES: '{pihole1="http://pihole01.telaranrhiod.space/admin/api.php"}'
      # PIHOLE_INSTANCES: '{pihole1="http://pihole01.telaranrhiod.space/admin/api.php",pihole2="http://pihole02.telaranrhiod.space/admin/api.php"}'
      VIRTUAL_HOST: "piholeInflux.telaranrhiod.space"
    dns_servers:
      - 10.1.1.171
      - 10.1.1.175
    network_mode: host
    domainname : telaranrhiod.space
  tags:
    - pihole
    - influxDB
