---
# tasks file for docker-minecraft
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/vaultwarden/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
  with_items:
    - data

- name: Recreate vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '3012'
      - '80'
    # ports:
    #   - '8888:80'
    volumes:
      - /docker/containers/vaultwarden/data:/data
    networks:
      - name: theways
    networks_cli_compatible: false
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      WEBSOCKET_ENABLED: "true"
      DATABASE_URL: "mysql://{{ vault_docker_vaultwarden_mysql_user }}:{{ vault_docker_vaultwarden_mysql_password }}@10.1.1.5:3306/vaultwarden"
  tags:
    - vaultwarden

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/vaultwarden.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/vaultwarden.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG