#!/usr/bin/env ansible-playbook
- name: "Install Docker helpers {{ansible_os_family}}"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - fail2ban-all
    - nano
    - wget
    - python-pip
    - git
