---

- name: "Install generic packages Debian"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # - fail2ban-all
    - nano
    - wget
    # - python-pip
    - git
    - tmux
    # - stow

...