---
# tasks file for docker-minecraft
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/minecraft/{{ item }}"
    state: directory
  with_items:
    - data
    - data/config
    - data/plugins
    - data/mods

- name: Recreate minecraft container
  docker_container:
    name: minecraft
    image: itzg/minecraft-server
    # version: latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '25565'
    published_ports:
      - 25562:25565
    volumes:
      - /docker/containers/minecraft/data:/data
    networks_cli_compatible: false
    env:
      # OPS: Findarato
      # TYPE: BUKKIT
      # TYPE: FORGE
      # TYPE: SPIGOT
      TYPE: PAPER
      ALLOW_NETHER: TRUE
      ENABLE_AUTOPAUSE: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      EULA: TRUE
      GID: 1000
      MEMORY: 8G
      MOTD: McHarryVille's Minecraft Server
      SERVER_PORT: 25566
      SNOOPER_ENABLED: FALSE
      TZ: "America/Chicago"
      UID: 1000
      REMOVE_OLD_MODS: TRUE
      SPIGET_RESOURCES: 9089,34315
  tags:
    - minecraft
