---
# tasks file for docker-minecraft
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/minecraft/{{ item }}"
    state: directory
  with_items:
    - data
    - data/config
    - data/plugins
    - data/mods

- name: Recreate minecraft container
  docker_container:
    name: minecraft
    image: itzg/minecraft-server
    # version: latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '25565'
    published_ports:
      - 25565:25565
    volumes:
      - /docker/containers/minecraft/data:/data
    networks_cli_compatible: false
    env:
      ALLOW_NETHER: "true"
      # ENABLE_AUTOPAUSE: "true"
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      GID: "1000"
      MEMORY: "8G"
      MOTD: "McHarryVille's Minecraft Server"
      # OPS: Findarato
      REMOVE_OLD_MODS: "true"
      SERVER_PORT: "25565"
      SNOOPER_ENABLED: "false"
      SPIGET_RESOURCES: "9089,34315,274"
      # SPIGET_RESOURCES: "274"
      # TYPE: "BUKKIT"
      # TYPE: "FORGE"
      # TYPE: "PAPER"
      # TYPE: "SPIGOT"
      TYPE: "VANILLA"
      TZ: "America/Chicago"
      UID: "1000"
  tags:
    - minecraft
