---
# tasks file for smokeping

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_smokeping_storage }}/{{ item }}"
    state: directory
    mode: "0775"
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - config
    - data
  tags:
    - smokeping

- name: Recreate smokeping container
  community.general.docker_container :
    name: smokeping
    image: linuxserver/smokeping
    state: started
    restart_policy: always
    recreate: yes
    restart: yes
    pull: true
    hostname: smokeping
    exposed_ports:
      - '80'
    volumes:
      - "{{ docker_smokeping_storage }}/config:/config"
      - "{{ docker_smokeping_storage }}/data:/data"
      - /etc/localtime:/etc/localtime:ro
    networks_cli_compatible: false
    networks:
      - name: theways
    dns_search_domains: "{{ smokeping_dns_domains }}"
    dns_servers: "{{ smokeping_dns_servers }}"
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Chicago"
  tags:
    - smokeping

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/smokeping.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/smokeping.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG
  tags:
    - smokeping
    - SWAG