---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/radarr/{{ item }}"
    state: directory
    mode: "0775"
    owner: "1000"
    group: docker
  with_items:
    - config

- name: 🛑 Stop Radarr container
  community.docker.docker_container:
    name: radarr
    state: stopped
  tags:
    - radarr

- name: 🔥 Remove Radarr container
  community.docker.docker_container:
    name: radarr
    state: absent
  tags:
    - radarr

- name: 🎥 Create NFS mount movies
  community.docker.docker_volume:
    name: nfs-movies
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: nfs
      o: "addr=10.1.1.7,rw"
      device: :/mnt/Dedicated/Storage/Movies/

- name: Remove Old Download
  community.docker.docker_volume:
    name: radarr-downloads
    state: absent

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: nfs
      o: "addr=10.1.1.5,rw"
      device: :/volume2/ssd.docker/torrents/downloads/complete/

- name: Recreate Radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '7878'
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - arr-downloads:/downloads
      - "nfs-movies:/movies"
      - "{{ docker_radarr_storage }}/config:/config"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - radarr

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/radarr.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/radarr.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG
  tags:
    - radarr
    - SWAG