- include_tasks: "{{ansible_os_family}}.yml"

- name: Create Docker paths
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /docker/containers
    - /docker/logs

# - name: Ensure docker is running

- name: Copy over cleanup script
  ansible.builtin.copy:
    src: cleanup_docker.sh
    dest: /usr/local/bin/cleanup_docker.sh

- name: Copy cleanup service
  ansible.builtin.copy:
    src: Clean-up-docker.service
    dest: /etc/systemd/system/Clean-up-docker.service
  notify:
    - restart systemD

- name: Copy cleanup timer
  ansible.builtin.copy:
    src: Clean-up-docker.timer
    dest: /etc/systemd/system/Clean-up-docker.timer
  notify:
    - restart systemD

- name: Enable cleanup timer
  ansible.builtin.systemd_service:
    state: started
    name: Clean-up-docker.timer
    daemon_reload: true
    enabled: true