---
# handlers file for docker-grafana
- name: Restart firewalld
  service:
    name: firewalld
    state: restarted


- name: restart SWAG
  community.docker.docker_container:
    name: swag
    restart: True