---
# tasks file for docker-grafana

- name: Create Docker paths
  file:
    path: "{{docker_storage_path}}{{ item }}"
    state: directory
    mode: 0775
    group: it
    owner: it
  with_items:
    - var
    - etc
    - plugins
    - root

- name: Create SNMP Paths
  file:
    path: "{{docker_storage_path}}/root/{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: root
  with_items:
    - .snmp/
    - .snmp/mibs/

- name: "Copying SNMP files"
  copy:
    src: "files/{{item}}"
    dest: "{{docker_storage_path}}/root/{{item}}"
    owner: root
    group: root
    mode: 0755
    # backup: yes
  with_items:
    - .snmp/snmp.conf
    - .snmp/mibs/powernet403.mib
    - .snmp/mibs/.index


- name: "Copying nagios plugins"
  copy:
    src: "files/plugins/{{item}}"
    dest: "{{docker_storage_path}}/plugins/{{item}}"
    owner: root
    group: it
    mode: 0755
    # backup: yes
  with_items:
    - check_snmp
    - check_smtp
    - check_dns
    - check_nrpe
    - check_sip
    - sip2info.py
    - sip2talk.py
    - slack_nagios.pl
  notify: Restart Nagios



- name: Clone nagios config from git
  git:
    repo: "{{nagios_git}}"
    dest: "{{docker_storage_path}}etc/"
    update: yes
    key_file: /home/it/.ssh/id_rsa
    version: docker
  notify: Restart Nagios

- name: Recreate Nagios container
  docker_container:
    name: nagios
    image: findarato/docker-nagios
    state: started
    restart_policy: unless-stopped
    recreate: yes
    exposed_ports:
      - 25
      - 80
    published_ports:
      - 25:25
      - 8080:80
    volumes:
      - "{{docker_storage_path}}etc/:/usr/local/nagios/etc"
      - "{{docker_storage_path}}plugins/:/usr/local/nagios/libexec/plugins"
      - "{{docker_storage_path}}root/:/root/"
    env:
      VIRTUAL_HOST: nagios.library.wpl.lib.in.us

- name: Open Ports for Nagios
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
