---
# tasks file for docker-piHole

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{docker_piHole_storage}}{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - etc-pihole
    - etc-dnsmasq.d
  tags:
    - pihole

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/pihole.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/pihole.subdomain.conf"
    mode: '0440'
  tags:
    - pihole
    - SWAG
  notify:
    - restart SWAG

- name: Recreate pihole container
  community.docker.docker_container:
    name: pihole
    hostname: "{{docker_pihole_virtual_hostname}}"
    image: pihole/pihole:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    shm_size: 500MB
    ports:
      - "53:53/tcp"
      - "8888:80/tcp"
      - "53:53/udp"
    exposed_ports:
      - "67/udp"
      - "80/tcp"
      - "443/tcp"
    volumes:
      - "{{docker_piHole_storage}}/etc-pihole:/etc/pihole/"
      - "{{docker_piHole_storage}}/etc-dnsmasq.d:/etc/dnsmasq.d/"
      - /etc/localtime:/etc/localtime:ro
    networks_cli_compatible: false
    networks:
      - name: theways
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    env:
      TZ: "America/Chicago"
      WEBPASSWORD: "{{ vault_pihole_webserver_password }}" # <= v6
      VIRTUAL_HOST: "{{ docker_pihole_virtual_host }}"
      hostname: "{{docker_pihole_virtual_hostname}}"
      FTLCONF_webserver_api_password: "{{ vault_pihole_webserver_password }}" # >= V6
      FTLCONF_dns_upstreams: "10.1.1.1" # >= V6
      FTLCONF_dns_listeningMode: 'all' # >= V6
      PIHOLE_UID: '1000' # >= V6
      PIHOLE_GID: '1000' # >= V6
  tags:
    - pihole

