---
# tasks file for docker-piHole

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Create Docker paths
  file:
    path: "/docker/containers/pihole/{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - config/pihole
    - config/dnsmasq.d
  tags:
    - pihole

- name: Recreate pihole container
  docker_container:
    name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    exposed_ports:
      - "67/udp"
      - "80/tcp"
      - "443/tcp"
    volumes:
      - /docker/containers/pihole/config/pihole:/etc/pihole/
      - /docker/containers/pihole/config/dnsmasq.d:/etc/dnsmasq.d/
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: "America/Chicago"
      VIRTUAL_HOST: "pihole01.telaranrhiod.space"
      WEBPASSWORD: password
    dns_servers:
      - 8.8.8.8
      - 1.1.1.1
  tags:
    - pihole

# - name: Create Pihole Network
#   docker_network:
#     name: pihole
#     connected:
#       - pihole
#       - pihole-influxDB
#     appends: yes

# - name: Open Ports for pihole
#   firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: enabled
#   with_items:
#     - "{{ docker_ports }}"
#   notify: Restart firewalld
#   tags:
#     - pihole