---
# tasks file for docker-piHole

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Create Docker paths
  file:
    path: "/docker/containers/jackett/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - downloads
    - config
  tags:
    - jackett

- name: Recreate jackett container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - 9117
    published_ports:
      - 9117:9117
    volumes:
      - /docker/containers/jackett/downloads:/downloads
      - /docker/containers/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: "America/Chicago"
      PUID: 1000
      PGID: 1000
  tags:
    - jackett

- name: Open Ports for jackett
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
  tags:
    - jackett