---
# tasks file for docker-dns

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Create Docker paths
  file:
    path: "{{ docker_dns_storage }}/{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - config
    - data

- name: Recreate Bind container
  docker_container:
    name: bind
    image: sameersbn/bind:latest
    state: started
    restart_policy: unless-stopped
    recreate: no
    restart: yes
    pull: false
    dns_servers: ["10.1.1.171","10.1.1.175"]
    ports:
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:10000:10000'
    volumes:
      - "{{ docker_dns_storage }}/data:/data"
    env:
      ROOT_PASSWORD: SecretPassword
      TZ: America/Chicago
      PUID: "1000"
      PGID: "1000"
      VERSION: latest

- name: Open Ports for Bind
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
