---
# tasks file for docker-deluge

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest


- name: Grow the Ways
  community.docker.docker_network:
    name: "{{ docker_network }}"

- name: Create Docker paths
  file:
    path: "/docker/containers/deluge/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - config
    - downloads
  tags:
    - deluge
    # - data/downloads/incomplete

- name: Create and Update Deluge Container
  community.docker.docker_container:
    name: deluge
    image: lscr.io/linuxserver/deluge:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    container_default_behavior: no_defaults
    exposed_ports:
      - "8112"
      - "58846"
      - "27975"
    published_ports:
      - 8112:8112
      - 27975:27975
      - 27975:27975/udp
      - 58846:58846
      - 58846:58846/udp
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - "/docker/containers/deluge/config:/config"
      - "/docker/containers/deluge/downloads:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Chicago"
      DELUGE_LOGLEVEL: error
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    networks:
      - name: theways
  tags:
    - deluge

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/deluge.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/deluge.subdomain.conf.sample"
    mode: '0440'
  notify:
    - Restart SWAG
  tags:
    - deluge
    - SWAG