---
# tasks file for docker-transmission

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest


- name: Grow the Ways
  community.docker.docker_network:
    name: "{{ docker_network }}"

- name: Create Docker paths
  file:
    path: "/docker/containers/deluge/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - config
  tags:
    - deluge
    # - data/downloads/incomplete

- name: Create and Update Deluge Container
  community.docker.docker_container:
    name: deluge
    image: lscr.io/linuxserver/deluge:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8112"
      - "27975"
    published_ports:
      - 8112:8112
      - 27975:27975
      - 27975:27975/udp
    volumes:
      - "/docker/containers/deluge/config:/config"
      - "/mnt/usb/docker/deluge/downloads:/downloads"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Chicago"
      # DELUGE_LOGLEVEL: error
      VIRTUAL_HOST: "deluge.telaranrhiod.space"
    networks:
      - name: theways
  tags:
    - deluge