---
# tasks file for docker-overseerr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest
  tags:
    - overseerr
    - arr

- name: Add overseerr to Arr network
  community.docker.docker_network:
    name: "{{ arr_network_name }}"
  tags:
    - overseerr
    - arr

- name: 'Create directory for container data'
  ansible.builtin.file:
    path: "{{ docker_data_dir }}/{{ dir }}"
    owner: 'docker'
    group: 'docker'
    mode: '0750'
    state: 'directory'
  loop:
    - 'overseerr_config'
  loop_control:
    loop_var: 'dir'
  tags:
    - overseerr
    - arr

- name: Recreate overseerr container
  community.docker.docker_container:
    name: overseerr
    image: lscr.io/linuxserver/overseerr
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    volumes:
      - /docker/containers/overseerr/config:/config
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: "{{ arr_network_name }}"
      - name: traefik_proxy
        aliases:
          - overseerr.mcharryville.space
          - overseerr.arr.mcharryville.space
          - overseerr
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      VERSION: latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.overseerr.rule: Host(`{{ overseerr_app_name }}.{{ traefik_domain }}`)
      traefik.http.routers.overseerr.tls: "true"
      traefik.http.routers.overseerr.entrypoints: websecure
      traefik.http.services.overseerr.loadbalancer.server.port: "5055"
  tags:
    - overseerr
    - arr
