---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: CentOS7
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
