---
# tasks file for docker-dns

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  ansible.builtin.file:
    path: "{{ docker_uptime_kuma_storage }}/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - /data
  tags:
    - uptime-kuma

- name: Recreate uptime-kuma container
  community.docker.docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "3001"
    volumes:
      - "{{ docker_uptime_kuma_storage }}/data:/app/data"
    networks_cli_compatible: false
    networks:
      - name: theways
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
    env:
      TZ: America/Chicago
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"

  tags:
    - uptime-kuma

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/uptime-kuma.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/uptime-kuma.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG
  tags:
    - uptime-kuma
    - SWAG
  when:
    - using_swag is true