- include: "{{ansible_os_family}}.yml"

- name: Ensure fail2ban pid directory exsists
  file:
    path: /var/run/fail2ban
    state: directory
    mode: 0755

- name: Start fail2ban
  systemd:
      name: fail2ban
      state: started
      enabled: yes
  tags: fail2ban, service

- name: Ntp Copy configuration file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp, service
  notify: Restart ntp

- name: Ntp start service
  systemd:
      name: ntp
      state: started
      enabled: yes
  tags: ntp
