---
# tasks file for docker-jacket

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

# - name: Grow the Ways
#   community.docker.docker_network:
#     name: "{{ docker-network }}"

- name: Grow the Ways
  community.docker.docker_network:
    name: "{{ docker_network }}"


- name: Create Docker paths
  file:
    path: "/docker/containers/jackett/{{ item }}"
    state: directory
    mode: "0775"
  with_items:
    - downloads
    - config
  tags:
    - jackett

- name: Recreate jackett container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "9117"
    # published_ports:
    #   - 9117:9117
    volumes:
      - /docker/containers/jackett/downloads:/downloads
      - /docker/containers/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      AUTO_UPDATE: 'true'
  tags:
    - jackett
