---
# tasks file for docker-transmission

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest


- name: Grow the Ways
  community.docker.docker_network:
    name: "{{ docker_network }}"

- name: Create Docker paths
  file:
    path: "{{ docker_dashy_storage }}/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - config
    - config/item-icons
  tags:
    - dashy

- name: Copy config file
  ansible.builtin.copy:
    src:  conf.yml
    dest: "{{ docker_dashy_storage }}/config/conf.yml"
    owner: "1000"
    group: "1000"
    force: no
  tags:
    - dashy


- name: Create and Update Dashy Container
  community.docker.docker_container:
    name: dashy
    image: lissy93/dashy
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "8080"
    volumes:
      - "{{ docker_dashy_storage }}/config/conf.yml:/app/public/conf.yml"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Chicago"
      VIRTUAL_HOST: "dashy.mcharryville.space"
      NODE_ENV: production
    networks_cli_compatible: false
    networks:
      - name: theways
    container_default_behavior: no_defaults
    log_driver: "{{ docker_log_driver }}"
    log_options: "{{ docker_log_options}}"
  tags:
    - dashy

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/dashy.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/dashy.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG
  tags:
    - dashy
    - SWAG

# - name: Fix configs for the dashy
#   ansible.builtin.lineinfile:
#     # backup: true
#     state: present
#     path: "{{ docker_proxy_config_storage }}/dashy.subdomain.conf"
#     regexp: '^        set $upstream_port 4000;'
#     line: '        set $upstream_port 80;'
#     backrefs: yes