---
# tasks file for docker-transmission

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest


- name: Grow the Ways
  community.docker.docker_network:
    name: "{{ docker_network }}"

- name: Create Docker paths
  file:
    path: "{{ docker_dashy_storage }}/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: yes
  with_items:
    - config
    - config/item-icons
  tags:
    - dashy

- name: Copy config file
  ansible.builtin.copy:
    src:  conf.yml
    dest: "{{ docker_dashy_storage }}/config/conf.yml"
    owner: "1000"
    group: "1000"
    force: no
  tags:
    - dashy


- name: Create and Update Dashy Container
  community.docker.docker_container:
    name: dashy
    image: lissy93/dashy
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - "80"
    published_ports:
      - "4000:80"
    volumes:
      - "{{ docker_dashy_storage }}/config/conf.yml:/app/public/conf.yml"
      # - "/docker/containers/dashy/config:/app/public"
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: "America/Chicago"
      VIRTUAL_HOST: "dashy.telaranrhiod.space"
      NODE_ENV: production
    networks_cli_compatible: false
    networks:
      - name: theways
    container_default_behavior: no_defaults
  tags:
    - dashy

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/dashy.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/dashy.subdomain.conf"
    mode: '0440'
  tags:
    - dashy
    - SWAG