---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_sonarr_storage }}{{ item }}"
    state: directory
  with_items:
    - config

- name: 🛑 Stop Sonarr container
  community.docker.docker_container:
    name: sonarr
    state: stopped
  tags:
    - sonarr

- name: 🔥 Remove Sonarr container
  community.docker.docker_container:
    name: sonarr
    state: absent
  tags:
    - sonarr

- name: 📺 Create NFS mount TV
  community.docker.docker_volume:
    name: nfs-tv
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: nfs
      o: "addr=10.1.1.7,rw"
      device: :/mnt/Dedicated/Storage/TV/

- name: Create NFS mount downloads
  community.docker.docker_volume:
    name: arr-downloads
    state: present
    driver: local
    recreate: options-changed
    driver_options:
      type: nfs
      o: "addr=10.1.1.5,rw"
      device: :/volume2/ssd.docker/torrents/downloads/complete/

- name: Remove Old Download
  community.docker.docker_volume:
    name: sonarr-downloads
    state: absent

- name: Recreate Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8989'
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - arr-downloads:/downloads
      - "nfs-tv:/tv"
      - "{{ docker_sonarr_storage }}/config:/config"
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - sonarr

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/sonarr.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/sonarr.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG