---
# tasks file for docker-sonarr
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "/docker/containers/sonarr/{{ item }}"
    state: directory
    # mode: 0775
    # group: docker
  with_items:
    - downloads
    - config

- name: Recreate sonarr container
  community.docker.docker_container:
    name: sonarr
    image: linuxserver/sonarr
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8989'
    volumes:
      # - /docker/containers/sonarr/downloads:/downloads
      - /mnt/whitetower/torrents/downloads:/downloads
      - /docker/containers/sonarr/config:/config
      - /mnt/storage/TV/:/tv/
    # mounts:
    #   - labels: transmission
    #     source: nfsvolume
    #     type: volume
    #     target: /downloads
    #     volume_driver: local
    #     volume_options:
    #       - type: 'nfs'
    #         device: ':/docker/containers/transmission/data/'
    #         addr: '10.1.1.33'
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - sonarr
