---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_sonarr_storage }}{{ item }}"
    state: directory
  with_items:
    - downloads
    - config

- name: Recreate Sonarr container
  community.docker.docker_container:
    name: Syncthing
    image: lscr.io/linuxserver/sonarr:latest
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8989'
    volumes:
      - /etc/localtime:/ect/localtime:ro
      - "{{ docker_sonarr_storage }}/downloads:/downloads"
      - "{{ docker_sonarr_storage }}/config:/config"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - sonarr

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/sonarr.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/sonarr.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG