---
# tasks file for docker-sonarr

- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{ docker_lidarr_storage }}/{{ item }}"
    state: directory
    mode: "0775"
    owner: "1000"
    group: docker
  with_items:
    - downloads
    - config

- name: Recreate lidarr container
  community.docker.docker_container:
    name: lidarr
    image: lscr.io/linuxserver/lidarr
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - '8686'
    volumes:
      - "{{ docker_lidarr_storage }}/downloads:/downloads"
      - "{{ docker_lidarr_storage }}/config:/config"
      - /mnt/storage/Music/download:/music
    dns_search_domains: "{{ dns_domains }}"
    dns_servers: "{{ dns_servers }}"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: '1000'
      PGID: '1000'
      VERSION: latest
  tags:
    - lidarr

- name: Download SWAG Config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/linuxserver/reverse-proxy-confs/master/lidarr.subdomain.conf.sample
    dest: "{{ docker_proxy_config_storage }}/lidarr.subdomain.conf"
    mode: '0440'
  notify:
    - Restart SWAG
  tags:
    - lidarr
    - SWAG