---
# tasks file for docker-grafana

- name: Create Docker paths
  file:
    path: "{{docker_storage_path}}{{ item }}"
    state: directory
    mode: 0775
    group: it
    owner: it
  with_items:
    - html
    - includes
    - ssl

- name: sync source from local directory
  synchronize:
      src: "files/proxy"
      dest: "{{docker_storage_path}}/html"
      delete: yes
      recursive: true
      rsync_opts:
        - "--exclude=.git"
    #     - "--exclude=*.pyc"
  become: no  # stops synchronize trying to sudo locally

# - name: Clone nagios config from git
#   git:
#     repo: "{{nagios_git}}"
#     dest: "{{docker_storage_path}}etc/"
#     update: yes
#     key_file: /home/it/.ssh/id_rsa
#     version: docker
#   #notify: Restart Nagios

- name: Recreate Nagios container
  docker_container:
    name: nginx-proxy
    image: nginx
    state: started
    restart_policy: unless-stopped
    recreate: true
    # pull: true
    exposed_ports:
       - 80
    published_ports:
      - 80:80
    volumes:
      - "{{docker_storage_path}}html/:/var/www/html/"
      - "{{docker_storage_path}}inclues/:/etc/nginx/includes/"
      - "{{docker_storage_path}}ssl/:/etc/ssl/certs/nginx/"

    # env:
    #   VIRTUAL_HOST: nagios.library.wpl.lib.in.us

- name: Open Ports for Nagios
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
