---
- name: Install Python tools for docker
  pip:
    name: docker
    state: latest

- name: Grow the Ways
  community.docker.docker_network:
    name: theways

- name: Create Docker paths
  file:
    path: "{{docker_storage}}/proxy/{{ item }}"
    state: directory
    mode: "0775"
    group: "1000"
    owner: "1000"
  with_items:
    - le/config

- name: Create SWAG
  community.general.docker_container:
    name: swag
    image: ghcr.io/linuxserver/swag
    state: started
    restart_policy: unless-stopped
    recreate: true
    pull: true
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "{{docker_storage}}/proxy/le/config:/config"
    networks_cli_compatible: false
    networks:
      - name: theways
    env:
      TZ: "America/Chicago"
      PUID: "1000"
      PGID: "1000"
      URL: "telaranrhiod.space"
      SUBDOMAINS: "wildcard"
      DNSPLUGIN: "digitalocean"
      VALIDATION: "dns"
      EMAIL: "findarato@gmail.com"
      STAGING: "false"